"""Adapter build framework.

Assembles one render context from the canonical sources (taxonomy.yml,
build/content.json, data/citation.yml, the skills' SKILL.md frontmatter
and the plugin's command files) and exposes a jinja2 environment over
adapters/templates/. Concrete targets (Copilot, Cursor, Codex, Gemini)
register themselves in TARGETS; the build command renders every target
into dist/<target>/.

Generated outputs land in dist/ and are never committed.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import frontmatter
import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

from .references import load_taxonomy, skill_page_ids
from .source import load_source


def _skill_entries(repo_root: Path, sources: list) -> list[dict]:
    """Merge every source's taxonomy and content into per-skill entries.

    Skills present on disk but mapped by no source (source-independent
    skills such as rseng-ai-declaration) are included with an empty pages
    list; their scope falls back to the coverage half of the frontmatter
    description.
    """
    entries: dict[str, dict] = {}
    for skill_md in sorted((repo_root / "skills").glob("*/SKILL.md")):
        meta = frontmatter.loads(skill_md.read_text(encoding="utf-8")).metadata
        description = " ".join(str(meta["description"]).split())
        entries[skill_md.parent.name] = {
            "name": skill_md.parent.name,
            "description": description,
            "scope": description.split(". Use", 1)[0].split(". This", 1)[0],
            "pages": [],
        }
    for source, content in sources:
        taxonomy = load_taxonomy(source.dir / "taxonomy.yml")
        for name, tax_entry in taxonomy.items():
            entry = entries[name]
            if tax_entry.get("scope"):
                entry["scope"] = " ".join(str(tax_entry["scope"]).split())
            entry["pages"].extend(
                {
                    "page_id": page_id,
                    "title": content["pages"][page_id]["title"],
                    "url": content["pages"][page_id]["rsqkit_url"],
                }
                for page_id in skill_page_ids(tax_entry)
            )
    return [entries[name] for name in sorted(entries)]


def _command_entries(repo_root: Path) -> list[dict]:
    commands = []
    for path in sorted((repo_root / "commands").glob("*.md")):
        post = frontmatter.loads(path.read_text(encoding="utf-8"))
        commands.append(
            {
                "name": path.stem,
                "description": str(post.metadata.get("description", "")),
                "body": post.content.strip(),
            }
        )
    return commands


def load_render_context(repo_root: Path) -> dict:
    """One context dict shared by every adapter template.

    Aggregates every installed content source; the first source acts as
    the primary one for the provenance stamp.
    """
    from .extension import list_extensions

    pipeline_dir = repo_root / "pipeline"
    names = list_extensions(repo_root)
    sources = []
    for name in names:
        source = load_source(repo_root, name)
        content = json.loads(
            (pipeline_dir / "build" / name / "content.json").read_text(encoding="utf-8")
        )
        sources.append((source, content))

    citations: dict[str, str] = {}
    notes = []
    for source, _content in sources:
        citation = yaml.safe_load(
            (source.dir / "data" / "citation.yml").read_text(encoding="utf-8")
        )
        for key, value in citation.items():
            text = " ".join(str(value).split())
            citations[key] = f"{citations[key]} {text}" if key in citations else text
        short_title = source.title.split("(")[0].strip()
        notes.append(f"{short_title} ({source.site}), {source.content_license}")

    generated_note = (
        "Generated by the rseng-agent-skills pipeline - do not edit. "
        f"Source: {'; '.join(notes)}."
    )
    source_stamps = [
        {
            "name": source.name,
            "short_title": source.title.split("(")[0].strip(),
            "commit": content["upstream"]["commit"],
            "license": source.content_license,
        }
        for source, content in sources
    ]
    return {
        "generated_note": generated_note,
        "upstream": sources[0][1]["upstream"],
        "sources": source_stamps,
        "citation": citations,
        "skills": _skill_entries(repo_root, sources),
        "commands": _command_entries(repo_root),
    }


def template_env(repo_root: Path) -> Environment:
    return Environment(
        loader=FileSystemLoader(repo_root / "adapters" / "templates"),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )


def copy_skills(repo_root: Path, target_dir: Path) -> None:
    """Passthrough: copy every skill folder (used by several targets)."""
    for skill_md in sorted((repo_root / "skills").glob("*/SKILL.md")):
        skill_dir = skill_md.parent
        shutil.copytree(skill_dir, target_dir / skill_dir.name, dirs_exist_ok=True)


def render_to(env: Environment, template_name: str, context: dict, out: Path) -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    text = env.get_template(template_name).render(**context)
    out.write_text(text.rstrip() + "\n", encoding="utf-8")
    return out


# target name -> build function(repo_root, env, context, dist_dir) -> list[Path]
TARGETS: dict = {}


def target(name: str):
    def register(fn):
        TARGETS[name] = fn
        return fn

    return register
