"""Adapter build framework.

Assembles one render context from the skills' SKILL.md frontmatter, the
relations graph and the plugin's command files, and exposes a jinja2
environment over adapters/templates/. Concrete targets (Copilot, Cursor,
Codex, Gemini) register themselves in TARGETS; the build command renders
every target into dist/<target>/.

Generated outputs land in dist/ and are never committed.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import frontmatter
from jinja2 import Environment, FileSystemLoader, StrictUndefined


def _brief(description: str) -> str:
    """Compact topic line: the first clause of the coverage half."""
    scope = description.split(". Use", 1)[0].split(". This", 1)[0]
    head = scope.split(": ", 1)[0].strip()
    if len(head) < len(scope) and len(head) <= 120:
        return head
    if len(scope) <= 120:
        return scope
    cut = scope[:120].rsplit(" ", 1)[0]
    return cut.rstrip(",;") + "..."


def _skill_entries(repo_root: Path) -> list[dict]:
    """Per-skill entries from SKILL.md frontmatter and the relations
    graph; the description's coverage half doubles as the scope."""
    related_file = repo_root / "hooks" / "related.json"
    related_map = (
        json.loads(related_file.read_text(encoding="utf-8"))
        if related_file.is_file()
        else {}
    )
    entries: dict[str, dict] = {}
    for skill_md in sorted((repo_root / "skills").glob("*/SKILL.md")):
        meta = frontmatter.loads(skill_md.read_text(encoding="utf-8")).metadata
        description = " ".join(str(meta["description"]).split())
        name = skill_md.parent.name
        entries[name] = {
            "name": name,
            "description": description,
            "scope": description.split(". Use", 1)[0].split(". This", 1)[0],
            "brief": _brief(description),
            "related": [
                {"name": rel, "reason": reason}
                for rel, reason in related_map.get(name, {}).items()
            ],
        }
    return [entries[name] for name in sorted(entries)]


def _command_entries(repo_root: Path) -> list[dict]:
    commands = []
    for path in sorted((repo_root / "commands").glob("*.md")):
        post = frontmatter.loads(path.read_text(encoding="utf-8"))
        commands.append(
            {
                "name": path.stem,
                "description": str(post.metadata.get("description", "")),
                "body": post.content.strip(),
            }
        )
    return commands


def load_render_context(repo_root: Path) -> dict:
    """One context dict shared by every adapter template."""
    return {
        "generated_note": "Generated by the rseng-agent-skills pipeline - do not edit.",
        "skills": _skill_entries(repo_root),
        "commands": _command_entries(repo_root),
    }


def template_env(repo_root: Path) -> Environment:
    return Environment(
        loader=FileSystemLoader(repo_root / "adapters" / "templates"),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )


def copy_skills(repo_root: Path, target_dir: Path) -> None:
    """Passthrough: copy every skill folder (used by several targets)."""
    for skill_md in sorted((repo_root / "skills").glob("*/SKILL.md")):
        skill_dir = skill_md.parent
        shutil.copytree(skill_dir, target_dir / skill_dir.name, dirs_exist_ok=True)


def copy_check(repo_root: Path, target_dir: Path) -> list[Path]:
    """Ship the platform-neutral self-check next to a target's context
    files: hookless agents are instructed to run it before finishing."""
    check_dir = target_dir / "rseng-check"
    check_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for src in (
        repo_root / "adapters" / "rseng_check.py",
        repo_root / "hooks" / "phases.json",
        repo_root / "hooks" / "related.json",
        repo_root / "hooks" / "signals.json",
    ):
        dest = check_dir / src.name
        shutil.copy(src, dest)
        written.append(dest)
    return written


def render_to(env: Environment, template_name: str, context: dict, out: Path) -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    text = env.get_template(template_name).render(**context)
    out.write_text(text.rstrip() + "\n", encoding="utf-8")
    return out


# target name -> build function(repo_root, env, context, dist_dir) -> list[Path]
TARGETS: dict = {}


def target(name: str):
    def register(fn):
        TARGETS[name] = fn
        return fn

    return register
