"""Adapter build framework.

Assembles one render context from the canonical sources (taxonomy.yml,
build/content.json, data/citation.yml, the skills' SKILL.md frontmatter
and the plugin's command files) and exposes a jinja2 environment over
adapters/templates/. Concrete targets (Copilot, Cursor, Codex, Gemini)
register themselves in TARGETS; the build command renders every target
into dist/<target>/.

Generated outputs land in dist/ and are never committed.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import frontmatter
import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

from .references import load_taxonomy, skill_page_ids
from .source import load_source


def _skill_entries(repo_root: Path, content: dict) -> list[dict]:
    from .extension import extension_dir

    taxonomy = load_taxonomy(extension_dir(repo_root) / "taxonomy.yml")
    entries = []
    for name, tax_entry in taxonomy.items():
        skill_md = repo_root / "skills" / name / "SKILL.md"
        meta = frontmatter.loads(skill_md.read_text(encoding="utf-8")).metadata
        pages = [
            {
                "page_id": page_id,
                "title": content["pages"][page_id]["title"],
                "url": content["pages"][page_id]["rsqkit_url"],
            }
            for page_id in skill_page_ids(tax_entry)
        ]
        entries.append(
            {
                "name": name,
                "description": " ".join(str(meta["description"]).split()),
                "scope": " ".join(str(tax_entry.get("scope", "")).split()),
                "pages": pages,
            }
        )
    return entries


def _command_entries(repo_root: Path) -> list[dict]:
    commands = []
    for path in sorted((repo_root / "commands").glob("*.md")):
        post = frontmatter.loads(path.read_text(encoding="utf-8"))
        commands.append(
            {
                "name": path.stem,
                "description": str(post.metadata.get("description", "")),
                "body": post.content.strip(),
            }
        )
    return commands


def load_render_context(repo_root: Path) -> dict:
    """One context dict shared by every adapter template."""
    pipeline_dir = repo_root / "pipeline"
    content = json.loads(
        (pipeline_dir / "build" / "content.json").read_text(encoding="utf-8")
    )
    from .extension import extension_dir

    citation = yaml.safe_load(
        (extension_dir(repo_root) / "data" / "citation.yml").read_text(encoding="utf-8")
    )
    source = load_source(repo_root)
    short_title = source.title.split("(")[0].strip()
    generated_note = (
        "Generated by the rseng-agent-skills pipeline - do not edit. "
        f"Source: {short_title} ({source.site}), {source.content_license}."
    )
    return {
        "generated_note": generated_note,
        "upstream": content["upstream"],
        "citation": {key: " ".join(str(v).split()) for key, v in citation.items()},
        "skills": _skill_entries(repo_root, content),
        "commands": _command_entries(repo_root),
    }


def template_env(repo_root: Path) -> Environment:
    return Environment(
        loader=FileSystemLoader(repo_root / "adapters" / "templates"),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )


def copy_skills(repo_root: Path, target_dir: Path) -> None:
    """Passthrough: copy the canonical skill folders (used by several targets)."""
    for skill_dir in sorted((repo_root / "skills").glob("rseng-*")):
        shutil.copytree(skill_dir, target_dir / skill_dir.name, dirs_exist_ok=True)


def render_to(env: Environment, template_name: str, context: dict, out: Path) -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    text = env.get_template(template_name).render(**context)
    out.write_text(text.rstrip() + "\n", encoding="utf-8")
    return out


# target name -> build function(repo_root, env, context, dist_dir) -> list[Path]
TARGETS: dict = {}


def target(name: str):
    def register(fn):
        TARGETS[name] = fn
        return fn

    return register
